name: enroll_neo_plugin_example
description: "Demonstrates how to use the enroll_neo_plugin plugin."
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  enroll_neo_plugin:
    path: ../


  cupertino_icons: ^1.0.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_dotenv: ^5.0.2


flutter:
#  assets:
#    - assets/config.json
#    - assets/config_dev.json

#  uses-material-design: true

